language: go
go:
  - 1.13.3
  - tip

sudo: false

before_install:
  - go get github.com/mattn/goveralls

install: true

script:
  - env GO111MODULES=on go build
  - env GO111MODULES=on go test

after_success:
  - goveralls -service=travis-ci
